# Site Build Settings

# # Jekyll-paginate-v2 configuration
# pagination:
#   enabled: false
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            100

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
url: "https://gebob19.github.io" # the base hostname & protocol for your site
plugins:             
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-scholar

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: 'Brennan Gebotys'
description: 'Machine Learning, Statistics, and All Things Cool'
author: 'Brennan Gebotys'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml